<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class SingleLandingSiteSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('single_landing_page')->delete();

        DB::table('single_landing_page')->insert(array (
  'hero_para' => 'Your ride in Bafoussam, fast and safe. Merci E — the smart taxi that takes you everywhere in the city.',
  'hero_img_1' => 'hero3.png',
  'hero_img_2' => 'herosec4.png',
  'hero_img_3' => 'mockuper.png',
  'hero_img_4' => 'hero4.png',
  'hero_img_5' => 'hero2.png',
  'adv_title' => 'Why Choose Merci E?',
  'adv_para' => 'A modern app designed for Bafoussam residents. Book, track, and arrive with confidence.',
  'adv_box1_title' => 'Taxi & Ride',
  'adv_box1_para' => 'Book a taxi in seconds. Our certified drivers take you anywhere in Bafoussam and surroundings safely.',
  'adv_box1_img' => 'vehicletype.mp4',
  'adv_box2_title' => 'Express Delivery',
  'adv_box2_para' => 'Send and receive packages quickly. Our delivery service covers the entire city for your daily errands.',
  'adv_box2_img' => 'live-tracking.mp4',
  'adv_box3_title' => 'Carpooling',
  'adv_box3_para' => 'Share rides and reduce costs. Merci E carpooling connects drivers and passengers on the same routes.',
  'adv_box3_img' => 'payment.mp4',
  'adv_box4_title' => 'Vehicle Rental',
  'adv_box4_para' => 'Rent a vehicle with or without a driver for your occasional needs: events, business trips or travel.',
  'adv_box4_img' => 'bidding.mp4',
  'adv_box5_title' => 'Mobile Money Payment',
  'adv_box5_para' => 'Pay easily via MTN Mobile Money or Orange Money. No need for cash, everything is done from your phone.',
  'adv_box5_img' => 'language.mp4',
  'app_works_title' => 'How Does Merci E Work?',
  'app_works_para' => 'Whether you are a passenger or a driver, our app is designed to simplify your life.',
  'app_works_user_title' => 'Passenger',
  'app_works_driver_title' => 'Driver',
  'user_box1_title' => 'Download the App',
  'user_box1_para' => 'Install Merci E on your Android or iPhone. Quick and free registration.',
  'user_box2_title' => 'Choose Your Destination',
  'user_box2_para' => 'Enter your pickup and destination anywhere in Bafoussam.',
  'user_box3_title' => 'Find a Driver',
  'user_box3_para' => 'A driver near you accepts your request in a few seconds.',
  'user_box4_title' => 'Ride and Pay',
  'user_box4_para' => 'Enjoy your ride and pay easily upon arrival via mobile money or cash.',
  'driver_box1_title' => 'Become a Partner',
  'driver_box1_para' => 'Sign up as a Merci E driver and start earning at your own pace.',
  'driver_box2_title' => 'Receive Trips',
  'driver_box2_para' => 'Requests come directly to your app. Accept based on your availability.',
  'driver_box3_title' => 'Navigate Easily',
  'driver_box3_para' => 'Follow the guided route to the passenger and destination in real time.',
  'driver_box4_title' => 'Get Paid',
  'driver_box4_para' => 'Receive payments directly to your mobile money account every week.',
  'app_user_img' => 'user-img.png',
  'app_driver_img' => 'driverimg1.png',
  'why_choose_title' => 'Why Merci E is the Best Choice?',
  'why_choose_box1_title' => 'All your rides in one tap',
  'why_choose_box1_para' => 'Taxi, delivery, carpooling and rental — all your transport needs in a single app.',
  'why_choose_box2_title' => 'Fair and transparent pricing',
  'why_choose_box2_para' => 'Prices are calculated upfront. No surprises, no negotiation. You know how much you pay before booking.',
  'why_choose_box3_title' => 'Verified drivers',
  'why_choose_box3_para' => 'All our drivers are trained and verified. Track your ride in real time and share your position with loved ones.',
  'why_choose_box4_title' => 'Available 24/7',
  'why_choose_box4_para' => 'Merci E is at your service day and night, 7 days a week. Need a taxi at 3am? We are here.',
  'why_choose_img' => 'useimagefinal.png',
  'about_title_1' => 'About',
  'about_title_2' => 'Merci E',
  'about_img' => 'aboutus1.png',
  'about_para' => 'Merci E is a Cameroonian startup born in Bafoussam with a simple vision: to make urban mobility accessible, safe, and affordable for everyone.',
  'ceo_title_1' => 'Our',
  'ceo_title_2' => 'Team',
  'ceo_para' => 'Driven by a young, dynamic team passionate about technology and transport, Merci E is committed to transforming the way people in Bafoussam get around.',
  'ceo_img' => 'aboutcompany4.png',
  'download_title' => 'Download Merci E Now',
  'download_para' => 'Available on Android and iOS. Join thousands of users in Bafoussam who trust Merci E for their daily commutes.',
  'download_user_link_android' => 'https://play.google.com/store/apps/details?id=cm.mercie.user',
  'download_user_link_apple' => 'https://apps.apple.com/app/merci-e/id0000000000',
  'download_driver_link_android' => 'https://play.google.com/store/apps/details?id=cm.mercie.driver',
  'download_driver_link_apple' => 'https://apps.apple.com/app/merci-e-driver/id0000000000',
  'download_img1' => 'mercie-user.png',
  'download_img2' => 'mercie-driver.png',
  'contact_heading' => 'Contact Us',
  'contact_para' => 'A question, suggestion, or need assistance? Our team is here for you.',
  'contact_img' => 'contactvideo.mp4',
  'contact_address_title' => 'Address',
  'contact_address' => 'Bafoussam, West Region, Cameroon',
  'contact_phone_title' => 'Phone',
  'contact_phone' => '+237 6XX XXX XXX',
  'contact_mail_title' => 'Email',
  'contact_mail' => 'contact@mercie.cm',
  'contact_web_title' => 'Website',
  'contact_web' => 'https://mercie.cm',
  'form_name' => 'Your Name',
  'form_mail' => 'Your Email',
  'form_subject' => 'Subject',
  'form_message' => 'Your Message',
  'form_btn' => 'Send',
  'locale' => 'en',
  'language' => 'English',
  'direction' => 'ltr',
  'created_at' => NULL,
  'updated_at' => '2026-06-09 13:53:56',
));

        DB::table('single_landing_page')->insert(array (
  'hero_para' => 'Votre trajet à Bafoussam, rapide et en toute sécurité. Merci E — le taxi intelligent qui vous accompagne partout dans la ville.',
  'hero_img_1' => 'hero3.png',
  'hero_img_2' => 'herosec4.png',
  'hero_img_3' => 'mockuper.png',
  'hero_img_4' => 'hero4.png',
  'hero_img_5' => 'hero2.png',
  'adv_title' => 'Pourquoi Choisir Merci E ?',
  'adv_para' => 'Une application moderne conçue pour les habitants de Bafoussam et des environs. Réservez, suivez et arrivez en toute confiance.',
  'adv_box1_title' => 'Taxi & VTC',
  'adv_box1_para' => 'Commandez un taxi en quelques secondes. Nos chauffeurs certifiés vous conduisent partout à Bafoussam et dans les environs en toute sécurité.',
  'adv_box1_img' => 'vehicletype.mp4',
  'adv_box2_title' => 'Livraison Express',
  'adv_box2_para' => 'Envoyez et recevez vos colis rapidement. Notre service de livraison couvre toute la ville pour vos courses du quotidien.',
  'adv_box2_img' => 'live-tracking.mp4',
  'adv_box3_title' => 'Covoiturage',
  'adv_box3_para' => 'Partagez vos trajets et réduisez vos coûts. Le covoiturage Merci E connecte conducteurs et passagers sur les mêmes itinéraires.',
  'adv_box3_img' => 'payment.mp4',
  'adv_box4_title' => 'Location de Véhicule',
  'adv_box4_para' => 'Louez un véhicule avec ou sans chauffeur pour vos besoins ponctuels : événements, déplacements professionnels ou voyages.',
  'adv_box4_img' => 'bidding.mp4',
  'adv_box5_title' => 'Paiement Mobile Money',
  'adv_box5_para' => 'Payez facilement via MTN Mobile Money ou Orange Money. Plus besoin de monnaie, tout se fait depuis votre téléphone.',
  'adv_box5_img' => 'language.mp4',
  'app_works_title' => 'Comment Fonctionne Merci E ?',
  'app_works_para' => 'Que vous soyez passager ou chauffeur, notre application est conçue pour vous simplifier la vie.',
  'app_works_user_title' => 'Passager',
  'app_works_driver_title' => 'Chauffeur',
  'user_box1_title' => 'Téléchargez l\'Application',
  'user_box1_para' => 'Installez Merci E sur votre téléphone Android ou iPhone. Inscription rapide et gratuite.',
  'user_box2_title' => 'Choisissez Votre Destination',
  'user_box2_para' => 'Entrez votre point de départ et votre destination n\'importe où à Bafoussam.',
  'user_box3_title' => 'Trouvez un Chauffeur',
  'user_box3_para' => 'Un chauffeur proche de vous accepte votre demande en quelques secondes.',
  'user_box4_title' => 'Voyagez et Payez',
  'user_box4_para' => 'Profitez de votre trajet et payez facilement à l\'arrivée via mobile money ou espèces.',
  'driver_box1_title' => 'Devenez Partenaire',
  'driver_box1_para' => 'Inscrivez-vous comme chauffeur Merci E et commencez à gagner à votre rythme.',
  'driver_box2_title' => 'Recevez des Courses',
  'driver_box2_para' => 'Les demandes arrivent directement sur votre application. Acceptez selon votre disponibilité.',
  'driver_box3_title' => 'Naviguez Facilement',
  'driver_box3_para' => 'Suivez l\'itinéraire guidé vers le passager et à destination en temps réel.',
  'driver_box4_title' => 'Encaissez Vos Gains',
  'driver_box4_para' => 'Recevez vos paiements directement sur votre compte mobile money chaque semaine.',
  'app_user_img' => 'user-img.png',
  'app_driver_img' => 'driverimg1.png',
  'why_choose_title' => 'Pourquoi Merci E est le Meilleur Choix ?',
  'why_choose_box1_title' => 'Tous vos trajets en un clic',
  'why_choose_box1_para' => 'Taxi, livraison, covoiturage et location — tous vos besoins de transport réunis dans une seule application.',
  'why_choose_box2_title' => 'Tarifs justes et transparents',
  'why_choose_box2_para' => 'Les prix sont calculés à l\'avance. Pas de surprise, pas de négociation. Vous savez combien vous payez avant de réserver.',
  'why_choose_box3_title' => 'Chauffeurs vérifiés',
  'why_choose_box3_para' => 'Tous nos chauffeurs sont formés et vérifiés. Suivez votre trajet en temps réel et partagez votre position avec vos proches.',
  'why_choose_box4_title' => 'Disponible 24h/24',
  'why_choose_box4_para' => 'Merci E est à votre service jour et nuit, 7 jours sur 7. Besoin d\'un taxi à 3h du matin ? On est là.',
  'why_choose_img' => 'useimagefinal.png',
  'about_title_1' => 'À Propos de',
  'about_title_2' => 'Merci E',
  'about_img' => 'aboutus1.png',
  'about_para' => 'Merci E est une startup camerounaise née à Bafoussam avec une vision simple : rendre la mobilité urbaine accessible, sûre et abordable pour tous. Notre plateforme connecte les passagers aux meilleurs chauffeurs de la région de l\'Ouest Cameroun.',
  'ceo_title_1' => 'Notre',
  'ceo_title_2' => 'Équipe',
  'ceo_para' => 'Portée par une équipe jeune, dynamique et passionnée par la technologie et le transport, Merci E s\'engage à transformer la manière dont les Bafoussaméens se déplacent.',
  'ceo_img' => 'aboutcompany4.png',
  'download_title' => 'Téléchargez Merci E Maintenant',
  'download_para' => 'Disponible sur Android et iOS. Rejoignez des milliers d\'utilisateurs à Bafoussam qui font confiance à Merci E.',
  'download_user_link_android' => 'https://play.google.com/store/apps/details?id=cm.mercie.user',
  'download_user_link_apple' => 'https://apps.apple.com/app/merci-e/id0000000000',
  'download_driver_link_android' => 'https://play.google.com/store/apps/details?id=cm.mercie.driver',
  'download_driver_link_apple' => 'https://apps.apple.com/app/merci-e-driver/id0000000000',
  'download_img1' => 'mercie-user.png',
  'download_img2' => 'mercie-driver.png',
  'contact_heading' => 'Contactez-Nous',
  'contact_para' => 'Une question, une suggestion ou besoin d\'assistance ? Notre équipe est là pour vous.',
  'contact_img' => 'contactvideo.mp4',
  'contact_address_title' => 'Adresse',
  'contact_address' => 'Bafoussam, Région de l\'Ouest, Cameroun',
  'contact_phone_title' => 'Téléphone',
  'contact_phone' => '+237 6XX XXX XXX',
  'contact_mail_title' => 'Email',
  'contact_mail' => 'contact@mercie.cm',
  'contact_web_title' => 'Site Web',
  'contact_web' => 'https://mercie.cm',
  'form_name' => 'Votre Nom',
  'form_mail' => 'Votre Email',
  'form_subject' => 'Objet',
  'form_message' => 'Votre Message',
  'form_btn' => 'Envoyer',
  'locale' => 'fr',
  'language' => 'French',
  'direction' => 'ltr',
  'created_at' => NULL,
  'updated_at' => '2026-06-09 13:53:41',
));

    }
}
