<?php

namespace App\Services;

use Illuminate\Support\Facades\Http;
use Illuminate\Support\Facades\Log;

class PawaPayService
{
    private string $baseUrl;
    private string $token;

    public function __construct()
    {
        // Prefer DB settings (set by admin), fall back to .env
        $environment   = get_payment_settings('pawapay_environment') ?? env('PAWAPAY_ENVIRONMENT', 'sandbox');
        $sandboxToken  = get_payment_settings('pawapay_sandbox_token') ?? '';
        $liveToken     = get_payment_settings('pawapay_live_token') ?? '';

        $this->token   = ($environment === 'live') ? $liveToken : $sandboxToken;
        $this->token   = $this->token ?: env('PAWAPAY_API_TOKEN', '');

        $this->baseUrl = ($environment === 'live')
            ? 'https://api.pawapay.io'
            : 'https://api.sandbox.pawapay.io';
    }

    public function getToken(): string
    {
        return $this->token;
    }

    // -------------------------------------------------------------------------
    // Deposits (recharge wallet)
    // -------------------------------------------------------------------------

    /**
     * Initiate a deposit (customer pays via mobile money).
     *
     * @param  string $depositId   UUIDv4 generated by us
     * @param  string $phone       Phone number e.g. 237612345678
     * @param  string $provider    e.g. MTN_MOMO_CMR or ORANGE_CMR
     * @param  string $amount      e.g. "5000"
     * @param  string $currency    e.g. "XAF"
     * @param  string $description Max 22 chars, alphanumeric + spaces
     */
    public function initiateDeposit(
        string $depositId,
        string $phone,
        string $provider,
        string $amount,
        string $currency,
        string $description = 'Merci E recharge'
    ): array {
        $payload = [
            'depositId'            => $depositId,
            'amount'               => $amount,
            'currency'             => $currency,
            'correspondent'        => $provider,
            'payer'                => [
                'type'    => 'MSISDN',
                'address' => ['value' => $phone],
            ],
            'customerTimestamp'    => now()->toISOString(),
            'statementDescription' => substr($description, 0, 22),
        ];

        $response = Http::withToken($this->token)
            ->post("{$this->baseUrl}/v2/deposits", $payload);

        Log::info('PawaPay deposit initiated', ['payload' => $payload, 'response' => $response->json()]);

        return $response->json() ?? [];
    }

    /**
     * Check the status of a deposit.
     */
    public function checkDepositStatus(string $depositId): array
    {
        $response = Http::withToken($this->token)
            ->get("{$this->baseUrl}/v2/deposits/{$depositId}");

        return $response->json()[0] ?? $response->json() ?? [];
    }

    // -------------------------------------------------------------------------
    // Payouts (driver withdrawal to mobile money)
    // -------------------------------------------------------------------------

    /**
     * Initiate a payout (we send money to the driver's mobile money).
     *
     * @param  string $payoutId    UUIDv4 generated by us
     * @param  string $phone       Phone number e.g. 237612345678
     * @param  string $provider    e.g. MTN_MOMO_CMR or ORANGE_CMR
     * @param  string $amount      e.g. "5000"
     * @param  string $currency    e.g. "XAF"
     * @param  string $message     4-22 chars, alphanumeric + spaces
     */
    public function initiatePayout(
        string $payoutId,
        string $phone,
        string $provider,
        string $amount,
        string $currency,
        string $message = 'Merci E retrait'
    ): array {
        $payload = [
            'payoutId'  => $payoutId,
            'amount'    => $amount,
            'currency'  => $currency,
            'recipient' => [
                'type'           => 'MMO',
                'accountDetails' => [
                    'phoneNumber' => $phone,
                    'provider'    => $provider,
                ],
            ],
            'customerMessage' => substr($message, 0, 22),
        ];

        $response = Http::withToken($this->token)
            ->post("{$this->baseUrl}/v2/payouts", $payload);

        Log::info('PawaPay payout initiated', ['payload' => $payload, 'response' => $response->json()]);

        return $response->json() ?? [];
    }

    /**
     * Check the status of a payout.
     */
    public function checkPayoutStatus(string $payoutId): array
    {
        $response = Http::withToken($this->token)
            ->get("{$this->baseUrl}/v2/payouts/{$payoutId}");

        return $response->json()[0] ?? $response->json() ?? [];
    }

    // -------------------------------------------------------------------------
    // Toolkit
    // -------------------------------------------------------------------------

    /**
     * Get active configuration (available providers, currencies, limits).
     */
    public function getActiveConfiguration(): array
    {
        $response = Http::withToken($this->token)
            ->get("{$this->baseUrl}/v2/active-configuration");

        return $response->json() ?? [];
    }
}
